### ISSUE TITLE
Migrate code from MicroProfile Config to this repo 

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse-ee4j/config#1]
Since this repo is to rehome MicroProfile Config to Jakarta EE. The first step is to create a baseline on Jakarta Config. I will create a PR for this baseline and then we can discuss to take in feedback.

**Comment by m0mus** [comment]
What kind of baseline you are talking about? IMO, we need to understand what we are trying to build. :)

We should start with:

1. Choose time slot suitable for all (most) of us to meet and setup weekly meetings.
2. Discuss how we want to collaborate (GitHub, mailing list, meeting minutes, etc.)
3. Discuss how we are going to vote.

On the first meeting we need to establish **goals and not goals** for Jakarta Config project. When it's done we can start talking about MP Config, namespaces, Maven coords etc. 

Here is a Doodle with meeting times proposal. Committers please respond. I can add more time slots if needed.
https://doodle.com/poll/8u2ezuf7pvksu846

**Comment by ljnelson** [comment]
> Since this repo is to rehome MicroProfile Config to Jakarta EE.

That is not what this repository is for. I support Dmitry's call for goals and non-goals above.

**Comment by keilw** [comment]
Well there would be at least a choice between:
- https://github.com/eclipse/ConfigJSR
- https://github.com/eclipse/microprofile-config

As a basis or inspiration.

**Comment by dmlloyd** [comment]
We absolutely should not under any circumstances start this project with a code dump.  I support Dimtry's idea to figure out what we're trying to do before we try to do it.

**Comment by keilw** [comment]
That's why I said "inspiration", the list is probably much longer including parts of Helidon or Tamaya amont others.😇

**Comment by Emily-Jiang** [comment]
well, we have to start from somewhere. Since this Jakarta Config is to collaborate with MP config, it is best to start with MP Config and work from there. We can discuss this either on the call or via the mailinglist.

**Comment by keilw** [comment]
Well I guess it's better to do it individually by "cherry picking" and not dump everything in and then keep removing stuff.

**Comment by Emily-Jiang** [comment]
By the way, moving MP Config should not be called dumping. It is served as baseline and facilitate the discussion. Anyway, we can discuss either on the call.

**Comment by keilw** [comment]
Well they are structurally quite different so it is better to do it iteratively after the calls.

**Comment by Emily-Jiang** [comment]
> What kind of baseline you are talking about? IMO, we need to understand what we are trying to build. :)
> 
> We should start with:
> 
>     1. Choose time slot suitable for all (most) of us to meet and setup weekly meetings.
I guess you meant the first meeting instead of weekly meetings. We need to discuss how frequent we want to meet: weekly, bi-weekly or ad hoc if we decide to collaborate via GitHub, mailing list, slack before setting up weekly calls.
> 
>     2. Discuss how we want to collaborate (GitHub, mailing list, meeting minutes, etc.)
Maybe slack channel as well.
>     3. Discuss how we are going to vote.
> 
> 
> On the first meeting we need to establish **goals and not goals** for Jakarta Config project. When it's done we can start talking about MP Config, namespaces, Maven coords etc.
> 
> I created an issue #2 (with Doodle poll) to choose a time slot.

**Comment by dmlloyd** [comment]
*Emily-Jiang* wrote:
> well, we have to start from somewhere.

Copying code over from MP is starting from the middle of the wrong path.  We don't and can't know what is appropriate without agreeing what the goals of the project are (and are not).  Let's do this one in the proper order, please!

*keilw* wrote:
> Well I guess it's better to do it individually by "cherry picking" and not dump everything in and then keep removing stuff.

Maybe not even that. Let's figure out the goals first!

*Emily-Jiang* wrote:
> By the way, moving MP Config should not be called dumping.

Why not?  I didn't realize that "code dump" is problematic or pejorative in any way; the term has a meaning and is widely used in the industry AFAICT.

> > ```
> > 2. Discuss how we want to collaborate (GitHub, mailing list, meeting minutes, etc.)
> > ```
> 
> Maybe slack channel as well.

Let's talk on the call before we commit to having to use yet another chat client. This isn't just an IBM project after all; some of us may not want to or be able to use Slack, and there are many better options than Slack anyway.

**Comment by struberg** [comment]
For the content: there is no need to be fully backward compat to MP-config or the lastest javax ConfigJSR proposal version. We should take the chance to review the aspects and if the community figures that neither of the fundamental mechanics of MP-config and javax.ConfigJSR should be pursued we can also get rid of the history.

I'd suggest the following steps:

1.) I'm with @m0mus: let's first look at the design. Let's write down which concepts we want to implement. I'd suggest reviewing mp-config/javax.ConfigJSR and other players again. Let's get back 5 years and first do the fast forward about all the different concepts on the market. What did work great? What did not work well?

2.) If we decide to keep the mp-config/javax.ConfigJSR concept (or at least the underlying basic concept) then @Emily-Jiang  is definitely right and we should imo take over the history. Anything else would create legal problems.

The 'code drop' has he benefit that the history of all the contributions and the way the got delivered gets preserved. This is important from a legal perspective to proof Code Provenance. I'd prefer to build on the original ConfigJSR repo because it has the full history. Remember that MP Config got initially dumped from file without having the full history either.

**Comment by dmlloyd** [comment]
> For the content: there is no need to be fully backward compat to MP-config or the lastest javax ConfigJSR proposal version. We should take the chance to review the aspects and if the community figures that neither of the fundamental mechanics of MP-config and javax.ConfigJSR should be pursued we can also get rid of the history.

It is not *possible* to be fully backwards compatible to MP config or the JSR since they would be in different package namespaces.

> I'd suggest the following steps:
> 
> 1.) I'm with @m0mus: let's first look at the design. Let's write down which concepts we want to implement. I'd suggest reviewing mp-config/javax.ConfigJSR and other players again. Let's get back 5 years and first do the fast forward about all the different concepts on the market. What did work great? What did not work well?
>
> 2.) If we decide to keep the mp-config/javax.ConfigJSR concept (or at least the underlying basic concept) then @Emily-Jiang is definitely right and we should imo take over the history. Anything else would create legal problems.

I am not a lawyer but have consulted with our lawyers on this topic in the past, and as far as I understand it, this is not in any way true.  Copyright is a fact, whether or not it is reflected or asserted by code history, file headers, or anything else.  AFAICT there is no valid legal reason that justifies bringing over history.

> The 'code drop' has he benefit that the history of all the contributions and the way the got delivered gets preserved. This is important from a legal perspective to proof Code Provenance. I'd prefer to build on the original ConfigJSR repo because it has the full history. Remember that MP Config got initially dumped from file without having the full history either.

One critical downside to this approach is having to roll forward all of the bug fixes from MP config.  But anyway I think some of the APIs will need to be rethought just based on the problems that have been uncovered along the way with MP Config's APIs and CDI integration.  And, all of that assumes that we would even retain the goal of providing a programmatic API and/or the CDI integration as it stands (and I think there's a very small chance that we wouldn't rethink *at least* the CDI integration because it is problematic at an implementation level).

Anyway this is all still premature discussion IMO.

**Comment by keilw** [comment]
>One critical downside to this approach is having to roll forward all of the bug fixes from MP config. But anyway I think some of >the APIs will need to be rethought just based on the problems that have been uncovered along the way with MP Config's APIs >and CDI integration. And, all of that assumes that we would even retain the goal of providing a programmatic API and/or the CDI >integration as it stands (and I think there's a very small chance that we wouldn't rethink at least the CDI integration because it is >problematic at an implementation level).

Sooner or later the MP config API and project should be replaced by the new Jakarta project anyway, so this is only for a very limited time, a release (like MP 5?) at most before MP should adopt Jakarta EE 10 and drop what it did earlier, same for MP Metrics btw. so this discussion is not only premature, some is only temporary IMO.
