### ISSUE TITLE
Jakarta Config meetings

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/config#2]
Let's use this issue for discussing time slots for Jakarta Config meetings.

Since Jakarta Config mailing list is not created yet, let's use this issue for discussing time slots for Jakarta Config meetings. I created a Doodle poll here:

https://doodle.com/poll/8u2ezuf7pvksu846

I added time slots which work for me (sorry about it), but I am fine to add more slots for consideration.

**Comment by Emily-Jiang** [comment]
Thank you @m0mus for creating the poll! I have created a [minutes doc ](https://docs.google.com/document/d/12_HdTKjkO_pxfeFsjtGXCsR-EaG42fblJNagvsSMyeE/edit?usp=sharing)for this meeting so that people can start adding agenda to the list.

**Comment by starksm64** [comment]
Where is the calendar with the meeting coordinates?

**Comment by joakime** [comment]
It was mentioned in the mailing list a while ago.

https://www.eclipse.org/lists/ee4j-pmc/msg03036.html

**Comment by Emily-Jiang** [comment]
@starksm64 the meeting is in [Jakarta EE specification meeting calendar](https://calendar.google.com/calendar/u/0/embed?src=eclipse-foundation.org_e9ki8t2gc75sh07qdh95c8ofvc@group.calendar.google.com&ctz=America/Toronto). By the way, this week's meeting has been cancelled because many attendees are on PTO.
